---
title: "Your Title Here"
author: 
  - name: Dr. Greg Chism
    affiliations:
      - name: School of Information, University of Arizona
description: "#TidyTuesday plot for ___"
format: 
  html:
    theme: Lux
    code-tools: true
execute:
  echo: true
  eval: true
  warning: false
  message: false
toc: true
categories: 
  - R
  - DataViz
  - "#TidyTuesday"
---

## Load packages

```{r}

if (!require(pacman))
  install.packages("pacman")

pacman::p_load(camcorder,
               gchismtt,
               glue,
               ggtext,
               patchwork,
               showtext,
               tidyverse
               )

```

## Load data

```{r}
tuesdata <- tidytuesdayR::tt_load(date_chr)
```

## Load fonts

```{r}
font_add_google("Roboto", "roboto")
showtext_auto()
```

## Define colours

```{r}
bg_col <- ""  # Specify background color
text_col <- ""  # Specify text color
highlight_col <- ""  # Specify highlight color
```

## Data wrangling

```{r}
# Add data wrangling code here
```

## Start recording

```{r}
#| eval: false
gg_record(
  dir = file.path(yr, date_chr, "recording"),
  device = "png",
  width = 7,
  height = 5,
  units = "in",
  dpi = 300
)
```

## Define text

```{r}
social <- gchismtt::social(
  bg_col = bg_col,
  icon_col = highlight_col,
  text_col = text_col,
  body_font = body_font
)

title <- ""  # Add your title here
st <- ""  # Add subtitle text here
cap <- paste0(
  "Data: <br>", social
)
```

## Plot

```{r}
# Add plotting code here

theme(
  plot.margin = margin(5, 5, 5, 5),
  plot.background = element_rect(fill = bg_col, colour = bg_col),
  panel.background = element_rect(fill = bg_col, colour = bg_col),
  plot.caption = element_textbox_simple(
    colour = text_col,
    hjust = 0.5,
    halign = 0.5,
    margin = margin(b = 10, t = 10),
    lineheight = 0.5,
    family = body_font
  )
)
```


## Save gif

```{r}
#| eval: false
gg_playback(
  name = file.path(yr, date_chr, paste0(date_strip, ".gif")),
  first_image_duration = 4,
  last_image_duration = 20,
  frame_duration = .25,
  background = bg_col
)
```

